# Generated by Django 5.0.2 on 2024-02-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userimage_is_borderized'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/original'),
        ),
    ]
