# Generated by Django 5.0.2 on 2024-02-26 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userimage_brightness_value_userimage_contrast_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='brightness_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-100)]),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='contrast_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-100)]),
        ),
    ]
