# Generated by Django 5.0.2 on 2024-02-26 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userimage_brightness_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='sharpness_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-100)]),
        ),
    ]
