# Generated by Django 5.0.2 on 2024-02-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userimage_sharpness_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='sharpness_value',
        ),
    ]
