# Generated by Django 5.0.6 on 2024-06-05 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userimage_brightness_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userimagegroup'),
        ),
    ]
