# Generated by Django 5.0.6 on 2024-06-07 10:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userimage_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userimagegroup',
            unique_together={('name', 'user')},
        ),
    ]
